require: rubocop-rails

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/migrate/**/*'
    - 'config/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
